steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args: ['-c', 'npm install']
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args:
      - -c
      - |
          echo "Running env injector"
          node set-env.js
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args: ['-c', 'npm run build --configuration=production']
  - name: 'node:20-alpine'
    entrypoint: 'node'
    args: ['set-env.js']
    secretEnv: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET']
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: gen-lang-client-0058436731
  _PLATFORM: managed
  _SERVICE_NAME: transaction-tracker-for-sheets
  _TRIGGER_ID: 0ea16ef2-064e-46e8-ae6e-0393e7ed4b6a
  _DEPLOY_REGION: europe-west1
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - transaction-tracker-for-sheets
availableSecrets:
  secretManager:
    - versionName: projects/372954632265/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: GOOGLE_CLIENT_ID
    - versionName: projects/372954632265/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: GOOGLE_CLIENT_SECRET
secretEnv:
  - GOOGLE_CLIENT_ID
  - GOOGLE_CLIENT_SECRET
