steps:
# Step 1: Install dependencies
- name: 'node:20-alpine'
  entrypoint: 'sh'
  args: ['-c', 'npm install']

# Step 2: Generate prod environment file with secrets
- name: 'node:20-alpine'
  entrypoint: 'node'
  args: ['set-env.js']

# Step 3: Build Angular app
- name: 'node:20-alpine'
  entrypoint: 'sh'
  args: ['-c', 'npm run build -- --configuration production']

# Optional: Deploy to GCS, Firebase, or any target
# - name: 'gcr.io/cloud-builders/gsutil'
#   args: ['cp', '-r', 'dist/*', 'gs://YOUR_BUCKET_NAME']

# Link Cloud Build environment variables to Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/372954632265/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: GOOGLE_CLIENT_ID
    - versionName: projects/372954632265/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: GOOGLE_CLIENT_SECRET
