steps:
  # STEP 1 — Install dependencies
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args: ['-c', 'npm install']

  # STEP 2 — Generate environment.prod.ts using Secret Manager values
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args:
      - -c
      - |
          echo "Running env injector"
          node set-env.js

  # STEP 3 — Build Angular app (PRODUCTION config)
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args: ['-c', 'npm run build --configuration=production']

# ENVIRONMENT SECRETS
availableSecrets:
  secretManager:
    - versionName: projects/372954632265/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: GOOGLE_CLIENT_ID
    - versionName: projects/372954632265/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: GOOGLE_CLIENT_SECRET

# ALLOW steps to access secrets
secretEnv:
  - GOOGLE_CLIENT_ID
  - GOOGLE_CLIENT_SECRET
