steps:
  # ---------------------------------------------------------
  # Install dependencies
  # ---------------------------------------------------------
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args:
      - -c
      - npm install
    secretEnv:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET

  # ---------------------------------------------------------
  # Generate environment.prod.ts using set-env.js
  # ---------------------------------------------------------
  - name: 'node:20-alpine'
    entrypoint: 'node'
    args: ['set-env.js']
    secretEnv:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET

  # ---------------------------------------------------------
  # Build Angular App (Production)
  # ---------------------------------------------------------
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args:
      - -c
      - npm run build --configuration production

  # ---------------------------------------------------------
  # Build Docker image
  # ---------------------------------------------------------
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - '-t'
      - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}"
      - .

  # ---------------------------------------------------------
  # Push Docker image
  # ---------------------------------------------------------
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}"

  # ---------------------------------------------------------
  # Deploy to Cloud Run
  # ---------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_SERVICE_NAME}
      - '--platform=managed'
      - "--image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}"
      - "--region=${_DEPLOY_REGION}"
      - '--quiet'

# ---------------------------------------------------------
# Image Output
# ---------------------------------------------------------
images:
  - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}"

# ---------------------------------------------------------
# Secret Manager → Build Step Environment Variables
# ---------------------------------------------------------
availableSecrets:
  secretManager:
    - versionName: projects/372954632265/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: GOOGLE_CLIENT_ID
    - versionName: projects/372954632265/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: GOOGLE_CLIENT_SECRET

# ---------------------------------------------------------
# Cloud Build Settings
# ---------------------------------------------------------
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: gen-lang-client-0058436731
  _SERVICE_NAME: transaction-tracker-for-sheets
  _DEPLOY_REGION: europe-west1
