steps:
  # Step 1: Install dependencies
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        npm install

  # Step 2: Inject secrets from Secret Manager
  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
        echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env

  # Step 3: Build Angular
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        npm run build

# Bind the secrets from Secret Manager to environment variables
availableSecrets:
  secretManager:
    - versionName: projects/372954632265/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: GOOGLE_CLIENT_ID
    - versionName: projects/372954632265/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: GOOGLE_CLIENT_SECRET
