const fs = require('fs');
const path = require('path');

console.log("🔧 Generating environment.prod.ts...");

const googleClientId = process.env.GOOGLE_CLIENT_ID;
const googleClientSecret = process.env.GOOGLE_CLIENT_SECRET;
const googleApiKey = process.env.GOOGLE_API_KEY;

// Validate secrets
if (!googleClientId || !googleClientSecret || !googleApiKey) {
  console.error("❌ ERROR: Missing required environment variables:");
  console.error("GOOGLE_CLIENT_ID:", googleClientId ? "OK" : "MISSING");
  console.error("GOOGLE_CLIENT_SECRET:", googleClientSecret ? "OK" : "MISSING");
  console.error("GOOGLE_API_KEY:", googleApiKey ? "OK" : "MISSING");
  process.exit(1);
}

// Target file path
const targetPath = path.join(
  __dirname,
  'src/environments/environment.prod.ts'
);

const envFileContent = `
// AUTO-GENERATED BY set-env.js — DO NOT EDIT MANUALLY

export const environment = {
  production: true,
  googleApiKey: '${googleApiKey}',
  googleClientId: '${googleClientId}',
  googleClientSecret: '${googleClientSecret}'
};
`;

try {
  fs.writeFileSync(targetPath, envFileContent);
  console.log(`✅ environment.prod.ts generated successfully at: ${targetPath}`);
} catch (err) {
  console.error("❌ Failed to write environment.prod.ts:", err);
  process.exit(1);
}
