const fs = require('fs');
const path = require('path');

console.log("🔧 Generating environment.prod.ts...");

const googleClientId = process.env.GOOGLE_CLIENT_ID;
const googleClientSecret = process.env.GOOGLE_CLIENT_SECRET;
const googleApiKey = process.env.GOOGLE_API_KEY;

const firebaseApiKey = process.env.FIREBASE_API_KEY;
const firebaseAuthDomain = process.env.FIREBASE_AUTH_DOMAIN;
const firebaseProjectId = process.env.FIREBASE_PROJECT_ID;
const firebaseStorageBucket = process.env.FIREBASE_STORAGE_BUCKET;
const firebaseMessagingSenderId = process.env.FIREBASE_MESSAGING_SENDER_ID;
const firebaseAppId = process.env.FIREBASE_APP_ID;
const firebaseMeasurementId = process.env.FIREBASE_MEASUREMENT_ID;

// Target file path
const targetPath = path.join(
  __dirname,
  'src/environments/environment.prod.ts'
);

const envFileContent = `
// AUTO-GENERATED BY set-env.js — DO NOT EDIT MANUALLY

export const environment = {
  production: true,
  googleApiKey: '${googleApiKey}',
  googleClientId: '${googleClientId}',
  googleClientSecret: '${googleClientSecret}',
  firebaseConfig: {
        apiKey: '${firebaseApiKey}',
        authDomain: '${firebaseAuthDomain}',
        projectId: '${firebaseProjectId}',
        storageBucket: '${firebaseStorageBucket}',
        messagingSenderId: '${firebaseMessagingSenderId}',
        appId: '${firebaseAppId}',
        measurementId: '${firebaseMeasurementId}'
    }
};
`;

try {
  fs.writeFileSync(targetPath, envFileContent);
  console.log(`✅ environment.prod.ts generated successfully at: ${targetPath}`);
} catch (err) {
  console.error("❌ Failed to write environment.prod.ts:", err);
  process.exit(1);
}
